'use strict';

const moment = require('moment');

module.exports = [
    {
        id: 1,
        name: 'user1',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 2,
        name: 'user2',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 3,
        name: 'user3',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 4,
        name: 'user4',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 5,
        name: 'user5',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 6,
        name: 'user6',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 7,
        name: 'user7',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 8,
        name: 'user8',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 9,
        name: 'user9',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    },
    {
        id: 10,
        name: 'user10',
        field1: 'data1',
        field2: 'data2',
        field3: 'data3',
        field4: 'data4',
        field5: 'data5',
        field6: 'data6',
        field7: 'data7',
        field8: 'data8',
        field9: 'data9',
        field10: 'data10',
        radio: true,
        checkbox: 'value1',
        dropdown: 'value1',
        createdAt: moment().unix(),
        updatedAt: moment().unix()
    }
];